<?php

use Drupal\l2\Event\TestContentSaveEvent;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function l2_theme($existing, $type, $theme, $path): array {
  return [
    'l2_table' => [
      'variables' => [
        'caption' => NULL,
        'rows' => NULL,
      ],
    ],
    'l2_number_transform' => [
      'variables' => [
        'number' => 0,
        'to' => 0,
        'transformed' => 0,
      ]
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function l2_node_presave(NodeInterface $node) {
  if ($node->getType() == 'test_content') {
    $event = new TestContentSaveEvent($node);
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event_dispatcher->dispatch($event, TestContentSaveEvent::EVENT_NAME);
  }
}
