<?php

use Drupal\l2\Event\TestContentSaveEvent;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function l2_theme($existing, $type, $theme, $path): array {
  return [
    'l2_table' => [
      'variables' => [
        'caption' => NULL,
        'rows' => NULL,
      ],
    ],
    'l2_number_transform' => [
      'variables' => [
        'number' => 0,
        'to' => 0,
        'transformed' => 0,
      ]
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function l2_node_presave(NodeInterface $node) {
  if ($node->getType() == 'test_content') {
    $event = new TestContentSaveEvent($node);
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event_dispatcher->dispatch($event, TestContentSaveEvent::EVENT_NAME);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function l2_node_update(NodeInterface $node) {
  if ($node->getType() == 'test_content') {
    \Drupal::moduleHandler()->invokeAll('test_content_updated', [$node]);
  }
}

/**
 * Implements hook_test_content_updated().
 */
function l2_test_content_updated(NodeInterface $node) {
  $count_symbols = strlen($node->body->value);
  \Drupal::messenger()->addMessage(t('Content "@title" contains @count symbols', [
    '@title' => $node->getTitle(),
    '@count' => $count_symbols,
  ]));
}
